### ISSUE TITLE
Wikitten not work on windows

### ISSUE THREAD

**Issue by Stephan123** [victorstanciu/Wikitten#64]
Hello,

i use wikitten on a linux server.
It works fine.

When i start the wiki on a windows server i get a error message.

PHP Fatal error:  Uncaught exception 'Exception' with message 'Page 'index.md' was not found' in C:\xampp\htdocs\wikitten\wiki.php:41

And here the trace:

Stack trace:
#0 C:\xampp\htdocs\wikitten\wiki.php(45): Wiki->{closure}()
#1 C:\xampp\htdocs\wikitten\wiki.php(331): Wiki->_render('index.md')
#2 C:\xampp\htdocs\wikitten\wiki.php(269): Wiki->indexAction()
#3 C:\xampp\htdocs\wikitten\index.php(52): Wiki->dispatch()
#4 {main}
  thrown in C:\xampp\htdocs\wikitten\wiki.php on line 41

Who can help?

Your sincerly

Stephan

**Comment by tamano** [comment]
Hi, Stephan

Do you have index.md in your LIBARY directory?
LIBARY directory might specified in your config.php and may be you should write the path in Windows way.

**Comment by AlgyTaylor** [comment]
Hi Stephan,

I had a similar problem, found I'd got a conflicting .htaccess file ... might be similar?

**Comment by fjxhkj** [comment]
vim config.php
uncomment the `define('ENABLE_EDITING', true);` line.
try again!
